# Generated by Django 3.2.13 on 2022-11-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountingredient',
            old_name='ingredient',
            new_name='name',
        ),
    ]
