# Generated by Django 3.2.13 on 2022-11-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_ingredient_amountingredient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountingredient',
            old_name='name',
            new_name='ingredient',
        ),
    ]
