# Generated by Django 3.2.13 on 2022-11-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_name_amountingredient_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/media/', verbose_name='Картинка'),
        ),
    ]
